{% set name = "Lagranto" %}
{% set version = "0.1.7" %}
{% set sha256 = "17babbf24a91760fdebc2deda10efd67b97399078721347052b9d49fa0ba4286"%}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://git.iac.ethz.ch/atmosdyn/Lagranto/repository/v{{version}}/archive.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win]


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - cartopy
    - netcdf4
    - path.py
    - matplotlib

test:
  imports:
    - lagranto
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - py.test
 
about:
  home: http://www.lagranto.ethz.ch
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Library to work with trajectories.'

  doc_url: https://lagranto.readthedocs.io/en/latest/
  dev_url: https://git.iac.ethz.ch/atmosdyn/Lagranto

extra:
  recipe-maintainers:
    - npiaget
    - michaesp
