{% set name = "Lagranto" %}
{% set version = "0.2.0" %}
{% set sha256 = "014ae176d59c7725e9b5a66fd50e8384640733cae3575feaf8167d9059351a5f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://git.iac.ethz.ch/atmosdyn/Lagranto/repository/v{{ version }}/archive.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy <1.14  # [py2k]
    - numpy  # [py3k]
    - cartopy
    - netcdf4
    - path.py
    - matplotlib-base

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    # FIXME - commenting out tests for python 2.7 due to bug in upstream package
    # See issue here: https://github.com/conda-forge/lagranto-feedstock/issues/9
    - export MPLBACKEND="AGG"
    - python -c 'import lagranto'
    - pytest  # [not py2k]

about:
  home: http://www.lagranto.ethz.ch
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Library to work with trajectories.
  doc_url: https://lagranto.readthedocs.io/en/latest/
  dev_url: https://git.iac.ethz.ch/atmosdyn/Lagranto

extra:
  recipe-maintainers:
    - npiaget
    - michaesp
