appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EP67SwmdNPxGuJPXPYZ6spVMNL23nX+FseaNCwqq8xMxMFnSlvkp1cc/VKCABMWmGLRtoHI8+aKF58Pu89gCcOc9nK3iG9zNcqFCxNo5EAfk/LogI5s5jBNyNxohEfRGCd/RwKRrwC/L8UNJviLz13GqAjrFlNWe4joZCuiK82ocY72k9SiYD+n2yCr+ZpqWpDc44V7blo8rVl6mU7QxyiGYD0OM0E6By7gbPAMcxkl+CP42YmxkeXa1E19NuRU2w9NoqIHgSNpTWkv7mK0Dj07mFR1jCukGznFf+/3d59z/t/ZDMTvjAZpYAvCHyCCLnkR8GnU0Ky/OHYEBc8bVDngLli3FvV404vDuXKHDsOcW6ON0M5vnns1FRAgQ46hhapSjKdmWXwxHPeEZGbreqxHUNI4YC7BxhjzMK+xjijncNiuPQugfwH3QWNQGlVddjqsxt+jCpnl22xENDyXTQcW/P+9IFq9s8EMmnM64MonbH/AM153HngP+K6p3yR6tvri/Kdn8zaRxFbEBRrn0gnw4leDhtqafztufbU2nZHbc8OLsrmUB3RB+Veg1+7NzJlXgSFPDLOJv5Y3zLPDplvJYAHZE9buY9BaT74cmwu8ljTWLYn1twC2kq5knY1TBY9qUIBcvehz4Px3tZQTHHftYB8pYJhwt7C5ve5aMf6U=}
